version: "{build}"
image: Visual Studio 2017
platform: x64
clone_folder: C:\gopath\src\github.com\src-d\ci
environment:
  GOPATH: C:\gopath
build: off
test_script:
  - set PATH=%GOPATH%\bin;C:\go\bin;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\msys64\usr\bin;%PATH%;"C:\Program Files\Git\mingw64\bin"
  - bash .tests.bash
deploy: off
